CREATE TABLE produtos (
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),
    preco NUMBER(18,2) NOT NULL,
    data_cadastro DATE DEFAULT SYSDATE
);

CREATE TABLE estoque_movimentacoes (
    id_movimentacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto NUMBER NOT NULL,
    tipo_movimentacao VARCHAR2(10) CHECK (tipo_movimentacao IN ('ENTRADA', 'SAIDA')),
    quantidade NUMBER NOT NULL,
    data_movimentacao DATE DEFAULT SYSDATE,
    CONSTRAINT fk_mov_prod FOREIGN KEY (id_produto) REFERENCES produtos(id_produto)
);

CREATE TABLE estoque_log (
    id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_movimentacao NUMBER,
    operacao VARCHAR2(10),
    data_log DATE DEFAULT SYSDATE
);